# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock.proto',
  package='stock',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstock.proto\x12\x05stock\x1a\x1bgoogle/protobuf/empty.proto\"\x10\n\x0e\x41\x63\x63ountRequest\"\x0e\n\x0c\x41\x63\x63ountReply\"\r\n\x0bTickRequest\"\x0b\n\tTickReply\"\x0e\n\x0c\x43hartRequest\"\x0c\n\nChartReply\"\x0f\n\rAccountsReply\"\x0c\n\nBuyRequest\"\n\n\x08\x42uyReply\"\r\n\x0bSellRequest\"\x0b\n\tSellReply2\xbe\x02\n\x05Stock\x12\x37\n\x07\x41\x63\x63ount\x12\x15.stock.AccountRequest\x1a\x13.stock.AccountReply\"\x00\x12\x30\n\x04Tick\x12\x12.stock.TickRequest\x1a\x10.stock.TickReply\"\x00\x30\x01\x12\x31\n\x05\x43hart\x12\x13.stock.ChartRequest\x1a\x11.stock.ChartReply\"\x00\x12:\n\x08\x41\x63\x63ounts\x12\x16.google.protobuf.Empty\x1a\x14.stock.AccountsReply\"\x00\x12+\n\x03\x42uy\x12\x11.stock.BuyRequest\x1a\x0f.stock.BuyReply\"\x00\x12.\n\x04Sell\x12\x12.stock.SellRequest\x1a\x10.stock.SellReply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ACCOUNTREQUEST = _descriptor.Descriptor(
  name='AccountRequest',
  full_name='stock.AccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=67,
)


_ACCOUNTREPLY = _descriptor.Descriptor(
  name='AccountReply',
  full_name='stock.AccountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=83,
)


_TICKREQUEST = _descriptor.Descriptor(
  name='TickRequest',
  full_name='stock.TickRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=98,
)


_TICKREPLY = _descriptor.Descriptor(
  name='TickReply',
  full_name='stock.TickReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=111,
)


_CHARTREQUEST = _descriptor.Descriptor(
  name='ChartRequest',
  full_name='stock.ChartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=127,
)


_CHARTREPLY = _descriptor.Descriptor(
  name='ChartReply',
  full_name='stock.ChartReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=141,
)


_ACCOUNTSREPLY = _descriptor.Descriptor(
  name='AccountsReply',
  full_name='stock.AccountsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=158,
)


_BUYREQUEST = _descriptor.Descriptor(
  name='BuyRequest',
  full_name='stock.BuyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=172,
)


_BUYREPLY = _descriptor.Descriptor(
  name='BuyReply',
  full_name='stock.BuyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=184,
)


_SELLREQUEST = _descriptor.Descriptor(
  name='SellRequest',
  full_name='stock.SellRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=199,
)


_SELLREPLY = _descriptor.Descriptor(
  name='SellReply',
  full_name='stock.SellReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['AccountRequest'] = _ACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['AccountReply'] = _ACCOUNTREPLY
DESCRIPTOR.message_types_by_name['TickRequest'] = _TICKREQUEST
DESCRIPTOR.message_types_by_name['TickReply'] = _TICKREPLY
DESCRIPTOR.message_types_by_name['ChartRequest'] = _CHARTREQUEST
DESCRIPTOR.message_types_by_name['ChartReply'] = _CHARTREPLY
DESCRIPTOR.message_types_by_name['AccountsReply'] = _ACCOUNTSREPLY
DESCRIPTOR.message_types_by_name['BuyRequest'] = _BUYREQUEST
DESCRIPTOR.message_types_by_name['BuyReply'] = _BUYREPLY
DESCRIPTOR.message_types_by_name['SellRequest'] = _SELLREQUEST
DESCRIPTOR.message_types_by_name['SellReply'] = _SELLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountRequest = _reflection.GeneratedProtocolMessageType('AccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.AccountRequest)
  })
_sym_db.RegisterMessage(AccountRequest)

AccountReply = _reflection.GeneratedProtocolMessageType('AccountReply', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTREPLY,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.AccountReply)
  })
_sym_db.RegisterMessage(AccountReply)

TickRequest = _reflection.GeneratedProtocolMessageType('TickRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.TickRequest)
  })
_sym_db.RegisterMessage(TickRequest)

TickReply = _reflection.GeneratedProtocolMessageType('TickReply', (_message.Message,), {
  'DESCRIPTOR' : _TICKREPLY,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.TickReply)
  })
_sym_db.RegisterMessage(TickReply)

ChartRequest = _reflection.GeneratedProtocolMessageType('ChartRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHARTREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.ChartRequest)
  })
_sym_db.RegisterMessage(ChartRequest)

ChartReply = _reflection.GeneratedProtocolMessageType('ChartReply', (_message.Message,), {
  'DESCRIPTOR' : _CHARTREPLY,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.ChartReply)
  })
_sym_db.RegisterMessage(ChartReply)

AccountsReply = _reflection.GeneratedProtocolMessageType('AccountsReply', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTSREPLY,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.AccountsReply)
  })
_sym_db.RegisterMessage(AccountsReply)

BuyRequest = _reflection.GeneratedProtocolMessageType('BuyRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUYREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.BuyRequest)
  })
_sym_db.RegisterMessage(BuyRequest)

BuyReply = _reflection.GeneratedProtocolMessageType('BuyReply', (_message.Message,), {
  'DESCRIPTOR' : _BUYREPLY,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.BuyReply)
  })
_sym_db.RegisterMessage(BuyReply)

SellRequest = _reflection.GeneratedProtocolMessageType('SellRequest', (_message.Message,), {
  'DESCRIPTOR' : _SELLREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.SellRequest)
  })
_sym_db.RegisterMessage(SellRequest)

SellReply = _reflection.GeneratedProtocolMessageType('SellReply', (_message.Message,), {
  'DESCRIPTOR' : _SELLREPLY,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.SellReply)
  })
_sym_db.RegisterMessage(SellReply)



_STOCK = _descriptor.ServiceDescriptor(
  name='Stock',
  full_name='stock.Stock',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=215,
  serialized_end=533,
  methods=[
  _descriptor.MethodDescriptor(
    name='Account',
    full_name='stock.Stock.Account',
    index=0,
    containing_service=None,
    input_type=_ACCOUNTREQUEST,
    output_type=_ACCOUNTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Tick',
    full_name='stock.Stock.Tick',
    index=1,
    containing_service=None,
    input_type=_TICKREQUEST,
    output_type=_TICKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Chart',
    full_name='stock.Stock.Chart',
    index=2,
    containing_service=None,
    input_type=_CHARTREQUEST,
    output_type=_CHARTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Accounts',
    full_name='stock.Stock.Accounts',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_ACCOUNTSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Buy',
    full_name='stock.Stock.Buy',
    index=4,
    containing_service=None,
    input_type=_BUYREQUEST,
    output_type=_BUYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Sell',
    full_name='stock.Stock.Sell',
    index=5,
    containing_service=None,
    input_type=_SELLREQUEST,
    output_type=_SELLREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOCK)

DESCRIPTOR.services_by_name['Stock'] = _STOCK

# @@protoc_insertion_point(module_scope)
